# -*- coding: utf-8 -*-
"""demographic_data_analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sTJRmbVsmRgGCUEF0qzB4ABbWZE5vwkY
"""

import pandas as pd

from google.colab import files

# Esto abrirá un diálogo para subir archivos desde tu computadora
uploaded = files.upload()

import pandas as pd

# Cargar el archivo CSV que subiste
df = pd.read_csv("adult.data.csv", header=None)

# Asignar nombres de columnas
df.columns = [
    "age", "workclass", "fnlwgt", "education", "education-num",
    "marital-status", "occupation", "relationship", "race", "sex",
    "capital-gain", "capital-loss", "hours-per-week", "native-country", "salary"
]

# Verificar que cargó correctamente
df.head()

def calculate_demographic_data(print_data=True):
    """
    Calculate demographic data using pandas
    """
    # Read data from file
    df = pd.read_csv("adult.data.csv")

    # Example calculations:

    # 1. Count of each race
    race_count = df['race'].value_counts()

    # 2. Average age of men
    average_age_men = round(df[df['sex'] == 'Male']['age'].mean(), 1)

    # 3. Percentage with Bachelor's degree
    percentage_bachelors = round(
        (df['education'] == 'Bachelors').mean() * 100, 1
    )

    # 4. Percentage of people with >50K salary by education
    higher_education = df[df['education'].isin(['Bachelors','Masters','Doctorate'])]
    lower_education = df[~df['education'].isin(['Bachelors','Masters','Doctorate'])]

    higher_education_rich = round(
        (higher_education['salary'] == '>50K').mean() * 100, 1
    )
    lower_education_rich = round(
        (lower_education['salary'] == '>50K').mean() * 100, 1
    )

    # 5. Minimum work hours per week
    min_work_hours = df['hours-per-week'].min()

    # 6. Percentage of rich among those who work minimum hours
    num_min_workers = df[df['hours-per-week'] == min_work_hours]
    rich_percentage = round(
        (num_min_workers['salary'] == '>50K').mean() * 100, 1
    )

    # 7. Country with highest percentage of rich people
    country_rich_percentage = (df[df['salary'] == '>50K']
                               .groupby('native-country').size() /
                               df.groupby('native-country').size() * 100)
    highest_earning_country = country_rich_percentage.idxmax()
    highest_earning_country_percentage = round(country_rich_percentage.max(), 1)

    # 8. Most popular occupation for those rich in India
    top_IN_occupation = df[(df['native-country'] == 'India') &
                            (df['salary'] == '>50K')]['occupation'].value_counts().idxmax()

    if print_data:
        print("Number of each race:\n", race_count)
        print("Average age of men:", average_age_men)
        print(f"Percentage with Bachelor's degrees: {percentage_bachelors}%")
        print(f"Percentage with higher education earning >50K: {higher_education_rich}%")
        print(f"Percentage without higher education earning >50K: {lower_education_rich}%")
        print("Min work hours:", min_work_hours)
        print(f"Percentage of rich among those who work fewest hours: {rich_percentage}%")
        print("Country with highest percentage of rich:", highest_earning_country)
        print(f"Highest percentage of rich people in country: {highest_earning_country_percentage}%")
        print("Top occupation in India for those earning >50K:", top_IN_occupation)

    return {
        'race_count': race_count,
        'average_age_men': average_age_men,
        'percentage_bachelors': percentage_bachelors,
        'higher_education_rich': higher_education_rich,
        'lower_education_rich': lower_education_rich,
        'min_work_hours': min_work_hours,
        'rich_percentage': rich_percentage,
        'highest_earning_country': highest_earning_country,
        'highest_earning_country_percentage': highest_earning_country_percentage,
        'top_IN_occupation': top_IN_occupation
    }

calculate_demographic_data()